// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Renders home page",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "/ route"
                ],
                "summary": "Home page",
                "responses": {
                    "200": {
                        "description": "Rendered page successefully"
                    }
                }
            }
        },
        "/htmx/change-message": {
            "post": {
                "description": "Updates message in home page",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "/ route"
                ],
                "summary": "Change message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name that will be in the new message",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated message successefully"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "Is this even working?",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
